config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'exams#index'

  resources :exams do
    resources :questions
  end

  resources :exams do
    resources :submissions
  end


  resources :questions do
    resources :answers
  end

  resources :user_exams
  resources :users

end

app/models/answer.rb
class Answer < ApplicationRecord
  # belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attempt.rb
class Attempt < ApplicationRecord
  belongs_to :user
  belongs_to :exam
end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :submissions, dependent: :destroy
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :name, presence: true

  def full_name
    "#{name}"
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :exam, dependent: :destroy
  # has_many :answers, dependent: :destroy
  # accepts_nested_attributes_for :answers, allow_destroy: true
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
  belongs_to :exam
end

app/models/take_exam.rb
class TakeExam < ApplicationRecord
  belongs_to :user
  belongs_to :exam
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :user
  belongs_to :exam
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tests
  has_many :submissions

  has_one :profile
  def has_profile?
      profile.present? && profile.persisted?
  end
  def full_name
      profile.full_name
  end

end

app/models/user_exam.rb
class UserExam < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :exam
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  def index
   @exam = Exam.find(params[:exam_id])
   @submission = Submission.all.where(exam_id: @exam)
  end

  def new
    @exam = Exam.find(params[:exam_id])
    @submission = @exam.submissions.new
    @questions_total = @exam.questions.all
    @questions = @exam.questions.all

  end

  def show
    @exam = Exam.find(params[:exam_id])
    @submission = @exam.submissions.find(params[:id])

    @questions = @exam.questions.all
  end

  def create
    exam = Exam.find(params[:exam_id])
    @submission = exam.submissions.create(submission_params)

    if @submission.save
      redirect_to action: "show", id: @submission
    else
      render :new
    end
  end

  private
  def submission_params
    params.require(:submission).permit(
      :exam_id,
      :user_id,
      ann: {}
    )
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/take_exams_helper.rb
module TakeExamsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/user_exams_helper.rb
module UserExamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/submissions/_answers_fields.html.erb
<% @questions.each do |question| %>
  <% question.answers.each_with_index do |answer, index| %>
    <p>
      <%= @answer = answer %>
      <span>
        <%= radio_button_tag "submission[answers][]", index %>
      </span>
    </p>
  <% end %>
<% end %>

app/views/submissions/_question.html.erb
<div id="all-questions"><% @questions.to_json %></div>
<% @questions.each_with_index do |question, index| %>
<div id="question_id" data-id="<%= index %>" class="step-pane active sample-pane question" data-step="<%= index + 1 %>">
  <h4><%= index + 1 %>) <%= question.title %></h4>
  <div id="question_type" value="<%= question.sort.first %>" data-id="<%= question.id %>"><%= question.sort.first %></div>





  <% if question.sort.first === "number" %>
    <hr>
    <% question.answers.each_with_index do |answer, index| %>
      <p>
        <% if index > 8 %>
        <%= number_field_tag("submission[ann][#{question.id}]") %>
        <% end %>
      </p>
    <% end %>

  <% elsif question.timer == true %>
  <hr>
    <% question.answers.each_with_index do |answer, index| %>
    <p>
      <% if index > 3 && index < 7 %>
        <%= radio_button_tag("submission[ann][#{question.id}]", answer) %>
        <%= label("answer_".concat(answer), answer) %>
      <% end %>
    </p>
  <% end %>

  <% elsif question.sort.first === "open_question"  %>
    <hr>
    <% question.answers.each_with_index do |answer, index| %>
    <p>
      <% if index < 4 %>
        <%= radio_button_tag("submission[ann][#{question.id}]", answer) %>
        <%= label("answer_".concat(answer), answer) %>
      <% end %>
    </p>
  <% end %>

  <% else %>
    <hr>
    <% question.answers.each_with_index do |answer, index| %>
    <p>
      <% if index > 6 && index < 9 %>
        <%= radio_button_tag("submission[ann][#{question.id}]", answer) %>
        <%= label("answer_".concat(answer), answer) %>
      <% end %>
    </p>
      <% end %>
  <% end %>


</div>
<% end %>

app/views/submissions/new.html.erb
<%= form_for [@exam, @submission]  do |f| %>
<div id="counter">0</div>
<div class="wizard" data-initialize="wizard" id="questionFrom">
<div class="steps-container" >
	<ul class="steps">
    <% @questions.each_with_index do |question, index| %>
		<li id="li-step" data-step="<%= index + 1 %>" class="active">
      <span id="step"><%= index + 1 %></span>
		</li>
      <%= content_tag "div", id:"questions", data:{questions: question} do %>
      <% end %>
    <% end %>

	</ul>
  <div class="step-content questions">
      <%= render "question" %>
  </div>
</div>

<div class="actions">
  	<button type="button" class="btn btn-default btn-prev">Prev</button>
    <button type="button" class="btn btn-primary btn-next">Next</button>
    <%= f.submit "Submit", class: "btn btn-primary btn-submit" %>
</div>
</div>
<%= f.hidden_field :user_id, :value => current_user.id %>
<% end %>

app/views/submissions/new.js.erb
<%= javascript_tag do %>
  window.submissionURL = "<%= j submission_url %>";
<% end %>

app/views/submissions/show.html.erb
<div class="row">
  <h4><%= @exam.title %></h4>
  <hr>
  <div class="result"></div><!-- the final result -->
  <% @gevaarsvragen = 0 %>
  <% @restvragen = 0 %>
  <% @exam.questions.each do |question| %>
    <p><% question.id %></p>
    <% @submission.ann.each do |key, value| %>
      <% @key = key %>
      <% if question.id == key.to_i %>
      <% @correct_answer == @given_anwer %> <!-- result true/false -->
      <% @given_anwer = value %> <!-- given answer -->
      <% @correct = question.correct.to_i - 1 %>
      <% @correct_answer = question.answers[@correct] %> <!-- correct answer -->
      <% if question.timer == true %>
        <% if @correct_answer == @given_anwer %>
          <% @gevaarsvragen = @gevaarsvragen + 1 %>
        <% end %>
      <% else %>
        <% if @correct_answer == @given_anwer %>
          <% @restvragen = @restvragen + 1 %>
        <% end %>
      <% end %><!-- if question.timer == true -->

      <!-- showing only the wrong answers! -->
      <% if @correct_answer != @given_anwer %>
        <div class="col-xs-12 antworden">
          <p><strong>Vraag:</strong> <%= question.title %></p>
          <p><strong>Uw antwoord:</strong> <%= @given_anwer = value %></p> <!-- given answer -->
          <p><strong>Goede antwoord:</strong> <%= @correct_answer = question.answers[@correct] %></p> <!-- correct answer -->
        </div>
      <% end %>
      <!-- end showing only the wrong answers! -->

      <% end %><!-- if question.id == key -->
    <% end %><!-- submission.ann.each -->
  <% end %><!-- exam.questions.each -->

  <% @gevaarsvragen %> <% @exam.questions.where(timer: true).length %>
  <% @restvragen %> <% @exam.questions.where(timer: false).length %>
  <% if @gevaarsvragen > (@exam.questions.where(timer: true).length - 1) && @restvragen > (@exam.questions.where(timer: false).length - 2) %>
    <div class="congratulations">
      <p>Congratulations!</p>
    </div>
  <% else %>
    <div class="try_again">
      <p>Try again</p>
    </div>
  <% end %>
</div>