config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'exams#index'

  resources :exams do
    resources :questions
  end

  resources :exams do
    resources :submissions
  end


  resources :questions do
    resources :answers
  end

  resources :user_exams
  resources :users

end

app/models/answer.rb
class Answer < ApplicationRecord
  # belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attempt.rb
class Attempt < ApplicationRecord
  belongs_to :user
  belongs_to :exam
end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :submissions, dependent: :destroy
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :name, presence: true

  def full_name
    "#{name}"
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :exam, dependent: :destroy
  # has_many :answers, dependent: :destroy
  # accepts_nested_attributes_for :answers, allow_destroy: true
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
  belongs_to :exam
end

app/models/take_exam.rb
class TakeExam < ApplicationRecord
  belongs_to :user
  belongs_to :exam
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :user
  belongs_to :exam
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tests
  has_many :submissions

  has_one :profile
  def has_profile?
      profile.present? && profile.persisted?
  end
  def full_name
      profile.full_name
  end

end

app/models/user_exam.rb
class UserExam < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :exam
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def index
     @exams = Exam.all
     @questions = Question.new
     @answers = Answer.new
   end

   def new
     @exam = Exam.new
   end

   def create
     @exam = Exam.new(exam_params)
     if @exam.save
       redirect_to @exam, notice: "Exam created!"
     else
       render :new
     end
   end

   def show
     @exam = Exam.find(params[:id])
     @questions = @exam.questions
     @question = Question.new

     @answers = @question.answers
     @answer = Answer.new

   end

   def destroy
     @exam = Exam.find(params[:id])
     @exam.destroy

     redirect_to action: "index"
   end

   private
   def exam_params
     params.require(:exam).permit(:title)
   end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/take_exams_helper.rb
module TakeExamsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/user_exams_helper.rb
module UserExamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exams/_answer.html.erb
<%= f.text_field :title, class: "form-control" , id: "title"%>

app/views/exams/_answer_fields.html.erb
<div class='nested-fields'>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :correct, 'correct' %>
    <%= f.radio_button :correct, "correct", id: "correct" %>
  </div>

  <br>
</div>

app/views/exams/_form.html.erb
<h3>Add new exam</h3>
<%= form_for Exam.new  do |f| %>
<%= f.text_field :title, class: "form-control" %>
<br>
<%= f.submit "Create", class: "btn btn-lg  btn-primary add-pair" %>
<% end %>

app/views/exams/_newQuestionForm.html.erb
<%= form_for [@exam, @question] do |f|  %>
  <div class="question-title">
    <%= f.label :title, 'Question' %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <hr>
  <div class="time" style="margin-top:20px;">
    <div class="form-check">
      <%= f.label 'Gevaarherkenning vragen' %> <br>
      <label class="form-check-label">
        <%= f.radio_button :timer, true, id: "time-yes", class: "form-check-input" %>
        Ja
      </label>
      <br>
      <label class="form-check-label">
        <%= f.radio_button :timer, false, id: "time-no", class: "form-check-input" %>
        Nee
      </label>
    </div>
    <hr>
  </div>


  <div class="question-sort form-check" style="margin-top:20px;">
    <%= f.label 'Questions type:' %> <br>
    <label class="form-check-label">
      <%= radio_button_tag 'question[sort][]','number', id: 'sort', class: "invullen form-check-input"%>
      Invullen
    </label>
    <br>
    <label class="form-check-label">
      <%= radio_button_tag 'question[sort][]','yes_no', id: 'sort', class: "form-check-input"%>
      Ja/Nee
    </label>
    <br>
    <label class="form-check-label">
      <%= radio_button_tag 'question[sort][]','open_question', id: 'sort', class: "form-check-input"%>
      [A,B,C] vragen
    </label>
    <hr>
  </div>


  <div class="answers form-check" style="margin-top:20px;">
    <%= f.label :answers %> <br>

    <%= f.text_field :answers, name: "question[answers][]", class: "form-check-input form-control" %>
    <label class="form-check-label">
      <%= f.radio_button :correct, "1"%>
      Goed
    </label>
    <br><br>

    <%= f.text_field :answers, name: "question[answers][]", class: "form-check-input form-control" %>
    <label class="form-check-label">
      <%= f.radio_button :correct, "2"%>
      Goed
    </label>
    <br><br>

    <%= f.text_field :answers, name: "question[answers][]", class: "form-check-input form-control" %>
    <label class="form-check-label">
      <%= f.radio_button :correct, "3"%>
      Goed
    </label>
    <br><br>

    <%= f.text_field :answers, name: "question[answers][]", class: "form-check-input form-control" %>
    <label class="form-check-label">
      <%= f.radio_button :correct, "4"%>
      Goed
    </label>
    <br>
  </div>

  <div class="answers-2 form-check" style="margin-top:20px;">
    <%= f.label :answers %> <br>

    <%= f.text_field :answers, name: "question[answers][]", value: "Remmen", class: "form-check-input form-control" %>
    <label class="form-check-label">
      <%= f.radio_button :correct, "5"%>
      Goed
    </label>
    <br><br>

    <%= f.text_field :answers, name: "question[answers][]",value: "Gas loslaten", class: "form-check-input form-control" %>
    <label class="form-check-label">
      <%= f.radio_button :correct, "6"%>
      Goed
    </label>
    <br><br>

    <%= f.text_field :answers, name: "question[answers][]",value: "Niets", class: "form-check-input form-control" %>
    <label class="form-check-label">
      <%= f.radio_button :correct, "7"%>
      Goed
    </label>
  </div>

  <div class="answers-ja form-check" style="margin-top:20px;">
    <%= f.label :answers %> <br>

    <%= f.text_field :answers, name: "question[answers][]", value: "Ja", class: "form-check-input form-control" %>
    <label class="form-check-label">
      <%= f.radio_button :correct, "8"%>
      Goed
    </label>
    <br><br>

    <%= f.text_field :answers, name: "question[answers][]",value: "Nee", class: "form-check-input form-control" %>
    <label class="form-check-label">
      <%= f.radio_button :correct, "9"%>
      Goed
    </label>
    <br><br>
  </div>

  <div class="answers-input form-check" style="margin-top:20px;">
    <p>Correct answer</p>
    <%= f.number_field :answers, name: "question[answers][]", class: "form-check-input form-control" %>
    <label class="form-check-label">
      <%= f.radio_button :correct, "10"%>
      Goed
    </label>
    <br><br>
  </div>

  <br>
  <br>
  <hr>

  <div class="submit">
    <%= f.submit 'Save', class: 'btn btn-success' %>
  </div>

<% end %>

app/views/exams/index.html.erb
<% @exams.each do |exam| %>
  <h4><%= link_to exam.title, exam_path(exam) %></h4>
<% end %>

app/views/exams/new.html.erb
<%= render 'form' %>

app/views/exams/show.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  Add new question
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add new question</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'newQuestionForm' %>
      </div>
    </div>
  </div>
</div>
<h2><%= @exam.title %></h2>
<br>
<%= link_to "Delete exam", exam_path(@exam.id), method: :delete, data: {confirm: "NOTE: Deleting an exam will delete all associated questions. \nDo you wish to continue?" }, class: "btn btn-danger" %>
<% @exam_path = exam_path(@exam.id) %>
<a href="<%= @exam_path %>/submissions/new">
  <button class="btn btn-success">Take exam</button>
</a>
<hr>